export const wordsWithHints = [
  { word: "about", hint: "concerning; on the subject of" },
  { word: "account", hint: "record of financial transactions" },
  { word: "across", hint: "from one side to the other" },
  { word: "addition", hint: "the process of combining numbers" },
  { word: "after", hint: "subsequent to; later in time" },
  { word: "again", hint: "once more; another time" },
  { word: "against", hint: "in opposition to" },
  { word: "agreement", hint: "a mutual arrangement or contract" },
  { word: "almost", hint: "nearly; not quite" },
  { word: "among", hint: "surrounded by; in the midst of" },
  { word: "amount", hint: "quantity or total" },
  { word: "amusement", hint: "something entertaining or fun" },
  { word: "angle", hint: "space between two intersecting lines" },
  { word: "angry", hint: "feeling or showing rage" },
  { word: "animal", hint: "living creature other than a plant" },
  { word: "answer", hint: "a reply or solution" },
  { word: "apparatus", hint: "equipment for a particular task" },
  { word: "apple", hint: "crisp red or green fruit" },
  { word: "approval", hint: "official consent or acceptance" },
  { word: "argument", hint: "verbal dispute or line of reasoning" },
  { word: "attack", hint: "an aggressive act" },
  { word: "attempt", hint: "an effort to do something" },
  { word: "attention", hint: "focused awareness" },
  { word: "authority", hint: "power or right to give orders" },
  { word: "automatic", hint: "working by itself with little input" },
  { word: "awake", hint: "not sleeping" },
  { word: "balance", hint: "state of equilibrium; evenness" },
  { word: "basin", hint: "bowl-shaped container or depression" },
  { word: "basket", hint: "woven container with handles" },
  { word: "beautiful", hint: "pleasing to the senses" },
  { word: "because", hint: "for the reason that" },
  { word: "before", hint: "earlier than; prior to" },
  { word: "behaviour", hint: "manner of acting" },
  { word: "belief", hint: "something accepted as true" },
  { word: "berry", hint: "small juicy fruit" },
  { word: "between", hint: "in the space separating two things" },
  { word: "birth", hint: "the act of being born" },
  { word: "bitter", hint: "sharp unpleasant taste" },
  { word: "black", hint: "darkest color; absence of light" },
  { word: "blade", hint: "sharp cutting edge of a knife" },
  { word: "blood", hint: "red fluid circulating in bodies" },
  { word: "board", hint: "flat piece of timber or panel" },
  { word: "boiling", hint: "very hot; at 100 °C for water" },
  { word: "bottle", hint: "container with a narrow neck" },
  { word: "brain", hint: "organ of thought" },
  { word: "brake", hint: "device that stops motion" },
  { word: "branch", hint: "limb of a tree" },
  { word: "brass", hint: "copper-zinc alloy; yellow metal" },
  { word: "bread", hint: "baked food made from dough" },
  { word: "breath", hint: "air taken into the lungs" },
  { word: "brick", hint: "rectangular block of baked clay" },
  { word: "bridge", hint: "structure spanning a gap" },
  { word: "bright", hint: "giving off much light" },
  { word: "broken", hint: "damaged; in pieces" },
  { word: "brother", hint: "male sibling" },
  { word: "brown", hint: "color made by mixing red and green" },
  { word: "brush", hint: "tool with bristles for cleaning" },
  { word: "bucket", hint: "open container for carrying liquids" },
  { word: "building", hint: "structure with walls and a roof" },
  { word: "burst", hint: "to explode or break open" },
  { word: "business", hint: "commercial or professional activity" },
  { word: "butter", hint: "spread made from churned cream" },
  { word: "button", hint: "fastener on clothing" },
  { word: "camera", hint: "device for taking photographs" },
  { word: "canvas", hint: "heavy cloth used by painters" },
  { word: "carriage", hint: "horse-drawn vehicle" },
  { word: "cause", hint: "reason something happens" },
  { word: "certain", hint: "sure; without doubt" },
  { word: "chain", hint: "series of linked metal rings" },
  { word: "chalk", hint: "soft white limestone used for writing" },
  { word: "chance", hint: "opportunity or luck" },
  { word: "change", hint: "to make different; coins" },
  { word: "cheap", hint: "low in price" },
  { word: "cheese", hint: "food made from curdled milk" },
  { word: "chemical", hint: "substance used in or produced by reactions" },
  { word: "chest", hint: "large storage box; torso area" },
  { word: "chief", hint: "leader or person in charge" },
  { word: "church", hint: "Christian place of worship" },
  { word: "circle", hint: "round plane figure" },
  { word: "clean", hint: "free from dirt" },
  { word: "clear", hint: "easy to see through; obvious" },
  { word: "clock", hint: "instrument for telling time" },
  { word: "cloth", hint: "fabric material" },
  { word: "cloud", hint: "visible water vapor in the sky" },
  { word: "collar", hint: "band around the neck of a shirt" },
  { word: "colour", hint: "hue perceived by the eye" },
  { word: "comfort", hint: "state of physical ease" },
  { word: "committee", hint: "group of people for a purpose" },
  { word: "common", hint: "shared; ordinary" },
  { word: "company", hint: "business organization" },
  { word: "complete", hint: "finished; whole" },
  { word: "complex", hint: "complicated; made of many parts" },
  { word: "condition", hint: "state of something; requirement" },
  { word: "conscious", hint: "aware and awake" },
  { word: "control", hint: "to regulate or command" },
  { word: "copper", hint: "reddish-brown metal, Cu" },
  { word: "cotton", hint: "soft fiber from a plant; used in textiles" },
  { word: "cough", hint: "sudden expulsion of air from lungs" },
  { word: "country", hint: "nation; rural area" },
  { word: "cover", hint: "something that lies on top" },
  { word: "crack", hint: "narrow break or split" },
  { word: "credit", hint: "purchasing power or recognition" },
  { word: "crime", hint: "an illegal act" },
  { word: "cruel", hint: "showing no mercy" },
  { word: "crush", hint: "press or squeeze with force" },
  { word: "current", hint: "present time; flow of electricity/water" },
  { word: "curtain", hint: "hanging drape for windows" },
  { word: "curve", hint: "bending line" },
  { word: "cushion", hint: "soft padded object to sit on" },
  { word: "damage", hint: "harm or injury" },
  { word: "danger", hint: "exposure to harm" },
  { word: "daughter", hint: "female child" },
  { word: "death", hint: "end of life" },
  { word: "decision", hint: "a choice made" },
  { word: "degree", hint: "unit of angle or temperature; academic award" },
  { word: "delicate", hint: "easily broken; fragile" },
  { word: "dependent", hint: "relying on something else" },
  { word: "design", hint: "plan or create the form of something" },
  { word: "desire", hint: "strong wish or want" },
  { word: "detail", hint: "small part of something" },
  { word: "different", hint: "not the same" },
  { word: "digestion", hint: "process of breaking down food" },
  { word: "direction", hint: "course along which something moves" },
  { word: "dirty", hint: "not clean" },
  { word: "discovery", hint: "finding something new" },
  { word: "disease", hint: "illness or disorder" },
  { word: "disgust", hint: "strong dislike or revulsion" },
  { word: "distance", hint: "space between two points" },
  { word: "division", hint: "act of separating; mathematical operation" },
  { word: "doubt", hint: "uncertainty or lack of belief" },
  { word: "drain", hint: "remove liquid; pipe that carries water away" },
  { word: "drawer", hint: "sliding box in furniture" },
  { word: "dress", hint: "garment for women; to clothe" },
  { word: "drink", hint: "liquid refreshment" },
  { word: "driving", hint: "operating a vehicle" },
  { word: "early", hint: "before the expected time" },
  { word: "earth", hint: "our planet" },
  { word: "education", hint: "process of learning" },
  { word: "effect", hint: "result or consequence" },
  { word: "elastic", hint: "stretchy material" },
  { word: "electric", hint: "powered by electricity" },
  { word: "engine", hint: "machine that converts energy to motion" },
  { word: "enough", hint: "sufficient quantity" },
  { word: "equal", hint: "the same in value or amount" },
  { word: "error", hint: "mistake" },
  { word: "event", hint: "occurrence; happening" },
  { word: "every", hint: "each one of a group" },
  { word: "example", hint: "illustration or sample" },
  { word: "exchange", hint: "trade one thing for another" },
  { word: "existence", hint: "state of being alive or real" },
  { word: "expansion", hint: "act of becoming larger" },
  { word: "expert", hint: "person with special skill or knowledge" },
  { word: "false", hint: "not true" },
  { word: "family", hint: "group of related people" },
  { word: "father", hint: "male parent" },
  { word: "feather", hint: "bird's body covering" },
  { word: "feeble", hint: "weak; lacking strength" },
  { word: "feeling", hint: "emotion or sensation" },
  { word: "female", hint: "opposite of male" },
  { word: "fertile", hint: "capable of producing abundantly" },
  { word: "fiction", hint: "literary works of imagination" },
  { word: "field", hint: "open land; area of study" },
  { word: "fight", hint: "physical or verbal combat" },
  { word: "finger", hint: "digit on the hand" },
  { word: "first", hint: "coming before all others" },
  { word: "fixed", hint: "fastened; not movable" },
  { word: "flame", hint: "burning gas from fire" },
  { word: "flight", hint: "act of flying" },
  { word: "floor", hint: "bottom surface of a room" },
  { word: "flower", hint: "bloom of a plant" },
  { word: "foolish", hint: "lack of good sense" },
  { word: "force", hint: "push or pull; strength" },
  { word: "forward", hint: "toward the front" },
  { word: "frame", hint: "structure that surrounds something" },
  { word: "frequent", hint: "happening often" },
  { word: "friend", hint: "person you are fond of" },
  { word: "front", hint: "forward part" },
  { word: "fruit", hint: "edible part of a plant with seeds" },
  { word: "future", hint: "time yet to come" },
  { word: "garden", hint: "area for growing plants" },
  { word: "general", hint: "widespread; military rank" },
  { word: "glass", hint: "transparent brittle material" },
  { word: "glove", hint: "hand covering with fingers" },
  { word: "grain", hint: "small hard seed; cereal crop" },
  { word: "grass", hint: "green ground cover plant" },
  { word: "great", hint: "very large or admirable" },
  { word: "green", hint: "color of healthy leaves" },
  { word: "group", hint: "collection of people or things" },
  { word: "growth", hint: "process of getting bigger" },
  { word: "guide", hint: "one who leads or directs" },
  { word: "hammer", hint: "tool with a heavy head" },
  { word: "hanging", hint: "suspended from above" },
  { word: "happy", hint: "feeling joy" },
  { word: "harbour", hint: "sheltered port for ships" },
  { word: "harmony", hint: "pleasing musical combination" },
  { word: "healthy", hint: "in good physical condition" },
  { word: "hearing", hint: "sense of sound" },
  { word: "heart", hint: "organ that pumps blood" },
  { word: "history", hint: "record of past events" },
  { word: "hollow", hint: "having an empty space inside" },
  { word: "horse", hint: "large four-legged animal ridden by people" },
  { word: "hospital", hint: "place for medical treatment" },
  { word: "house", hint: "building for people to live in" },
  { word: "humour", hint: "quality of being amusing" },
  { word: "important", hint: "of great significance" },
  { word: "impulse", hint: "sudden urge to act" },
  { word: "increase", hint: "make or become larger" },
  { word: "industry", hint: "economic activity of processing goods" },
  { word: "insect", hint: "small six-legged creature" },
  { word: "insurance", hint: "protection against financial loss" },
  { word: "interest", hint: "curiosity; charge for borrowing money" },
  { word: "invention", hint: "newly created device or idea" },
  { word: "island", hint: "land surrounded by water" },
  { word: "jelly", hint: "gelatinous fruit spread" },
  { word: "jewel", hint: "precious stone" },
  { word: "journey", hint: "act of traveling from place to place" },
  { word: "judge", hint: "public official in court; to form an opinion" },
  { word: "kettle", hint: "container for boiling water" },
  { word: "knife", hint: "cutting tool with a blade" },
  { word: "knowledge", hint: "information and understanding" },
  { word: "language", hint: "system of spoken or written communication" },
  { word: "laugh", hint: "express amusement with sound" },
  { word: "learning", hint: "acquiring knowledge" },
  { word: "leather", hint: "material made from animal hide" },
  { word: "letter", hint: "written message sent to someone" },
  { word: "level", hint: "flat even surface; a stage or rank" },
  { word: "library", hint: "place where books are kept" },
  { word: "light", hint: "illumination; opposite of heavy" },
  { word: "limit", hint: "point beyond which something may not pass" },
  { word: "linen", hint: "fabric made from flax fibers" },
  { word: "liquid", hint: "state of matter that flows" },
  { word: "little", hint: "small in size or amount" },
  { word: "living", hint: "alive; residence" },
  { word: "loose", hint: "not tight" },
  { word: "machine", hint: "device using power to perform tasks" },
  { word: "manager", hint: "person who supervises others" },
  { word: "market", hint: "place for buying and selling" },
  { word: "married", hint: "joined in matrimony" },
  { word: "match", hint: "contest; thin stick for making fire" },
  { word: "material", hint: "substance from which things are made" },
  { word: "measure", hint: "determine size, amount, or degree" },
  { word: "medical", hint: "relating to medicine" },
  { word: "meeting", hint: "gathering of people" },
  { word: "memory", hint: "ability to recall information" },
  { word: "metal", hint: "shiny conductive element" },
  { word: "middle", hint: "central point" },
  { word: "military", hint: "armed forces" },
  { word: "minute", hint: "sixty seconds; very small" },
  { word: "mixed", hint: "combined or blended" },
  { word: "money", hint: "medium of exchange" },
  { word: "monkey", hint: "primate with a tail" },
  { word: "month", hint: "roughly four weeks" },
  { word: "morning", hint: "part of day before noon" },
  { word: "mother", hint: "female parent" },
  { word: "motion", hint: "movement" },
  { word: "mountain", hint: "large natural elevation of the earth" },
  { word: "mouth", hint: "opening in the face for eating" },
  { word: "muscle", hint: "tissue that contracts for movement" },
  { word: "music", hint: "organized sound with melody or rhythm" },
  { word: "narrow", hint: "not wide" },
  { word: "nation", hint: "country or people" },
  { word: "natural", hint: "existing in nature" },
  { word: "necessary", hint: "required; essential" },
  { word: "needle", hint: "thin pointed sewing tool" },
  { word: "nerve", hint: "fiber that transmits signals in the body" },
  { word: "night", hint: "period of darkness after sunset" },
  { word: "noise", hint: "unwanted sound" },
  { word: "normal", hint: "usual; standard" },
  { word: "north", hint: "opposite of south" },
  { word: "number", hint: "mathematical value" },
  { word: "offer", hint: "present for acceptance" },
  { word: "office", hint: "place where business is done" },
  { word: "operation", hint: "surgical procedure; organized activity" },
  { word: "opinion", hint: "personal view or belief" },
  { word: "opposite", hint: "completely different" },
  { word: "orange", hint: "citrus fruit; color between red and yellow" },
  { word: "order", hint: "arrangement; command" },
  { word: "ornament", hint: "item used to decorate" },
  { word: "other", hint: "different from the one mentioned" },
  { word: "owner", hint: "person who possesses something" },
  { word: "paint", hint: "colored liquid for coating surfaces" },
  { word: "paper", hint: "thin sheets made from pulp" },
  { word: "parallel", hint: "lines that never meet" },
  { word: "parcel", hint: "package for mailing" },
  { word: "paste", hint: "thick soft mixture; glue" },
  { word: "payment", hint: "act of paying money" },
  { word: "peace", hint: "freedom from conflict" },
  { word: "pencil", hint: "graphite writing instrument" },
  { word: "person", hint: "human being" },
  { word: "physical", hint: "relating to the body" },
  { word: "picture", hint: "visual representation" },
  { word: "place", hint: "location or position" },
  { word: "plane", hint: "flat surface; aircraft" },
  { word: "plant", hint: "living organism that photosynthesizes" },
  { word: "plate", hint: "flat dish" },
  { word: "please", hint: "polite request word; satisfy" },
  { word: "pleasure", hint: "feeling of enjoyment" },
  { word: "plough", hint: "farm tool for tilling soil" },
  { word: "pocket", hint: "small pouch in clothing" },
  { word: "point", hint: "sharp tip; idea expressed" },
  { word: "poison", hint: "substance causing harm if ingested" },
  { word: "polish", hint: "make shiny; substance for shining" },
  { word: "political", hint: "relating to government" },
  { word: "porter", hint: "person who carries luggage" },
  { word: "position", hint: "place or posture" },
  { word: "possible", hint: "able to be done" },
  { word: "potato", hint: "starchy underground tuber" },
  { word: "powder", hint: "dry particles like flour" },
  { word: "power", hint: "ability to do or act; electricity" },
  { word: "present", hint: "current time; a gift" },
  { word: "price", hint: "cost of something" },
  { word: "print", hint: "produce text or images on paper" },
  { word: "prison", hint: "place for incarcerating criminals" },
  { word: "private", hint: "not public; soldier rank" },
  { word: "probable", hint: "likely to happen" },
  { word: "process", hint: "series of actions toward a result" },
  { word: "produce", hint: "manufacture; fresh fruits and vegetables" },
  { word: "profit", hint: "financial gain" },
  { word: "property", hint: "something owned; characteristic" },
  { word: "prose", hint: "ordinary written language" },
  { word: "protest", hint: "expression of objection" },
  { word: "public", hint: "open to all; opposite of private" },
  { word: "purpose", hint: "reason for doing something" },
  { word: "quality", hint: "degree of excellence" },
  { word: "question", hint: "inquiry" },
  { word: "quick", hint: "fast" },
  { word: "quiet", hint: "absence of noise" },
  { word: "quite", hint: "completely; fairly" },
  { word: "range", hint: "variety; set of mountains" },
  { word: "reaction", hint: "response to stimulus" },
  { word: "reading", hint: "act of interpreting written words" },
  { word: "ready", hint: "prepared" },
  { word: "reason", hint: "cause or explanation" },
  { word: "receipt", hint: "proof of payment" },
  { word: "record", hint: "documented information; vinyl disc" },
  { word: "regret", hint: "feeling of remorse" },
  { word: "regular", hint: "normal or repeated pattern" },
  { word: "relation", hint: "connection between things; family member" },
  { word: "religion", hint: "system of faith and worship" },
  { word: "request", hint: "ask for something" },
  { word: "respect", hint: "esteem or regard" },
  { word: "reward", hint: "prize given for effort" },
  { word: "rhythm", hint: "pattern of beats in music" },
  { word: "right", hint: "correct; opposite of left" },
  { word: "river", hint: "large natural flowing waterway" },
  { word: "rough", hint: "uneven; not smooth" },
  { word: "round", hint: "circular shape" },
  { word: "scale", hint: "device for weighing; proportion" },
  { word: "school", hint: "place for education" },
  { word: "science", hint: "systematic study of the natural world" },
  { word: "scissors", hint: "tool for cutting paper" },
  { word: "screw", hint: "metal fastener with helical ridge" },
  { word: "second", hint: "unit of time; after first" },
  { word: "secret", hint: "kept hidden" },
  { word: "secretary", hint: "administrative assistant" },
  { word: "selection", hint: "act of choosing" },
  { word: "sense", hint: "faculty like sight or taste" },
  { word: "separate", hint: "keep apart" },
  { word: "serious", hint: "solemn; important" },
  { word: "servant", hint: "person employed to serve others" },
  { word: "shade", hint: "relative darkness under cover" },
  { word: "shake", hint: "tremble or agitate" },
  { word: "shame", hint: "painful feeling of guilt" },
  { word: "sharp", hint: "having a keen edge or point" },
  { word: "sheep", hint: "wool-producing farm animal" },
  { word: "shelf", hint: "flat storage ledge" },
  { word: "shirt", hint: "upper-body garment" },
  { word: "shock", hint: "sudden surprise; electrical jolt" },
  { word: "short", hint: "opposite of long" },
  { word: "silver", hint: "precious gray-white metal" },
  { word: "simple", hint: "easy; not complex" },
  { word: "sister", hint: "female sibling" },
  { word: "skirt", hint: "women's lower-body garment" },
  { word: "sleep", hint: "state of rest for the body" },
  { word: "slope", hint: "inclined surface" },
  { word: "small", hint: "little in size" },
  { word: "smash", hint: "break violently" },
  { word: "smell", hint: "odor; sense detected by nose" },
  { word: "smile", hint: "facial expression showing pleasure" },
  { word: "smoke", hint: "visible vapor from fire" },
  { word: "smooth", hint: "having an even surface" },
  { word: "snake", hint: "legless reptile" },
  { word: "sneeze", hint: "sudden expulsion of air through nose/mouth" },
  { word: "society", hint: "community of people" },
  { word: "solid", hint: "state of matter with definite shape" },
  { word: "sound", hint: "vibrations perceived by ears" },
  { word: "south", hint: "opposite of north" },
  { word: "space", hint: "vast expanse beyond Earth; area" },
  { word: "spade", hint: "tool for digging" },
  { word: "special", hint: "unusual; out of the ordinary" },
  { word: "sponge", hint: "porous material that absorbs liquid" },
  { word: "spoon", hint: "utensil with a shallow bowl" },
  { word: "spring", hint: "season after winter; coil that bounces" },
  { word: "square", hint: "four equal sides; 90° corners" },
  { word: "stage", hint: "raised platform for performances" },
  { word: "stamp", hint: "postage label; to press down" },
  { word: "start", hint: "begin" },
  { word: "statement", hint: "declaration" },
  { word: "station", hint: "place where transport stops" },
  { word: "steam", hint: "water vapor from boiling" },
  { word: "steel", hint: "strong iron alloy" },
  { word: "stick", hint: "thin branch; adhere" },
  { word: "sticky", hint: "adhesive to the touch" },
  { word: "stiff", hint: "not easily bent" },
  { word: "still", hint: "not moving; nevertheless" },
  { word: "stitch", hint: "loop of thread in sewing" },
  { word: "stocking", hint: "close-fitting leg garment" },
  { word: "stomach", hint: "organ for digesting food" },
  { word: "stone", hint: "hard solid mineral matter" },
  { word: "store", hint: "shop; keep for future use" },
  { word: "story", hint: "narrative tale" },
  { word: "straight", hint: "not curved" },
  { word: "strange", hint: "unusual or unfamiliar" },
  { word: "street", hint: "public road in a city" },
  { word: "stretch", hint: "extend to full length" },
  { word: "strong", hint: "having great power" },
  { word: "structure", hint: "arrangement of parts; building" },
  { word: "substance", hint: "type of matter" },
  { word: "sudden", hint: "happening quickly and unexpectedly" },
  { word: "sugar", hint: "sweet crystalline substance" },
  { word: "summer", hint: "season after spring" },
  { word: "support", hint: "bear weight; give assistance" },
  { word: "surprise", hint: "unexpected event" },
  { word: "sweet", hint: "having sugar-like taste" },
  { word: "system", hint: "set of connected parts forming a whole" },
  { word: "table", hint: "piece of furniture with a flat top" },
  { word: "taste", hint: "sense detected by tongue" },
  { word: "teaching", hint: "act of instructing" },
  { word: "tendency", hint: "inclination toward a behavior" },
  { word: "theory", hint: "explanatory framework" },
  { word: "there", hint: "in that place" },
  { word: "thick", hint: "opposite of thin" },
  { word: "thing", hint: "object or item" },
  { word: "thought", hint: "idea or mental process" },
  { word: "thread", hint: "thin strand of fiber" },
  { word: "throat", hint: "passage from mouth to stomach/lungs" },
  { word: "through", hint: "from one side to the other" },
  { word: "thumb", hint: "short thick first digit" },
  { word: "thunder", hint: "loud sound after lightning" },
  { word: "ticket", hint: "paper granting entry or travel" },
  { word: "tight", hint: "closely fitting" },
  { word: "tired", hint: "in need of rest" },
  { word: "together", hint: "with each other" },
  { word: "tomorrow", hint: "day after today" },
  { word: "tongue", hint: "muscular organ in the mouth" },
  { word: "tooth", hint: "hard structure in the mouth" },
  { word: "touch", hint: "sense felt by skin" },
  { word: "trade", hint: "buying and selling" },
  { word: "train", hint: "rail transport vehicle; teach skills" },
  { word: "transport", hint: "carry goods or people" },
  { word: "trick", hint: "deceitful act or clever stunt" },
  { word: "trouble", hint: "difficulty or problem" },
  { word: "trousers", hint: "garment covering the legs" },
  { word: "twist", hint: "bend in a spiral shape" },
  { word: "umbrella", hint: "portable rain shield" },
  { word: "under", hint: "below or beneath" },
  { word: "value", hint: "worth or importance" },
  { word: "verse", hint: "line of poetry; opposite of prose" },
  { word: "vessel", hint: "container or ship" },
  { word: "violent", hint: "using physical force" },
  { word: "voice", hint: "sound produced in the larynx" },
  { word: "waiting", hint: "act of staying until something happens" },
  { word: "waste", hint: "unused material; squander" },
  { word: "watch", hint: "timepiece worn on wrist; observe" },
  { word: "water", hint: "H₂O; essential liquid" },
  { word: "weather", hint: "state of the atmosphere" },
  { word: "weight", hint: "how heavy something is" },
  { word: "wheel", hint: "circular device that rolls" },
  { word: "where", hint: "in what place" },
  { word: "while", hint: "period of time; during" },
  { word: "whistle", hint: "high-pitched sound or device" },
  { word: "white", hint: "color of fresh snow; absence of hue" },
  { word: "window", hint: "opening in a wall for light" },
  { word: "winter", hint: "coldest season of the year" },
  { word: "woman", hint: "adult human female" },
  { word: "wound", hint: "injury to tissue" },
  { word: "writing", hint: "act of putting words on paper" },
  { word: "wrong", hint: "incorrect" },
  { word: "yellow", hint: "color of ripe bananas" },
  { word: "yesterday", hint: "day before today" },
  { word: "young", hint: "not old; youthful" },
];
